import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import { Container, Heading, VStack } from '@chakra-ui/react';
import ChatBox from '../components/Chat/ChatBox/ChatBox';
import ChatInput from '../components/Chat/ChatInput/ChatInput';
import { Message } from '../components/Chat/types';

export default function Home() {
  const [messages, setMessages] = useState<Message[]>([]);

  const handleSendMessage = (newMessage: string) => {
    const messageObject = {
      text: newMessage,
      isBot: false, // Asumimos que todos los mensajes son del usuario por ahora
    };
    setMessages([...messages, messageObject]);
    // Aquí llamarías a tu API para obtener la respuesta del bot y actualizar el estado de messages
  };
  return (
    <div>
      <Head>
        <title>ItesaChallenguer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW='container.md' centerContent p={4}>
      <VStack spacing={8} w='100%'>
        <Heading>Chat con IA</Heading>
        <ChatBox messages={messages} />
        <ChatInput onSendMessage={handleSendMessage} />
      </VStack>
    </Container>
    </div>
  )
}
